name: Snyk Security Scan
on: [push]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Snyk test
        uses: snyk/actions/node@master
        timeout-minutes: 5  # Cancela si excede 5 minutos
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor  # Más rápido que 'test'
          args: --severity-threshold=high --detection-depth=3
